export const OK_BUTTON_PRESSED = 'OK_BUTTON_PRESSED';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SIGN_IN_BUTTON_PRESSED = 'SIGN_IN_BUTTON_PRESSED';
export const SIGN_UP_BUTTON_PRESSED = 'SIGN_UP_BUTTON_PRESSED';