export const OK_BUTTON_PRESSED = 'OK_BUTTON_PRESSED';
export const SIGN_IN_BUTTON_PRESSED = 'SIGN_IN_BUTTON_PRESSED';
export const SIGN_UP_BUTTON_PRESSED = 'SIGN_UP_BUTTON_PRESSED';

export const SIGN_IN_VALIDATION_PASSED = 'SIGN_IN_VALIDATION_PASSED';
export const SIGN_UP_VALIDATION_PASSED = 'SIGN_UP_VALIDATION_PASSED';
export const PASS_VALIDATION_PASSED = 'PASS_VALIDATION_PASSED';

export const SIGN_IN_VALIDATION_FAILED = 'SIGN_IN_VALIDATION_FAILED';
export const SIGN_UP_VALIDATION_FAILED = 'SIGN_UP_VALIDATION_FAILED';
export const PASS_VALIDATION_FAILED = 'PASS_VALIDATION_FAILED';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

